#!/usr/bin/env python
import sys
import os
import re
sys.path.insert(0, 'lib')
import helpers

_re_integer = re.compile('^[0-9]+$')

while True:
    try:
        input = raw_input("Enter a simple expression: ").strip()
    except KeyboardInterrupt:
        print 
        input = None
    if not input:
        break
    pieces = filter(None, input.split())
    if len(pieces) != 3:
        print "Bogus expression (wrong number of pieces)."
        continue
    arg1 = arg2 = None
    try:
        arg1 = pieces[0]
        arg2 = pieces[2]
        if _re_integer.match(arg1) and _re_integer.match(arg2):
            arg1 = int(arg1)
            arg2 = int(arg2)
        else:
            arg1 = float(arg1)
            arg2 = float(arg2)
    except:
        print "Non-numerical operands."
        continue
    op = pieces[1]
    if op == '-':
        print helpers.subtract(arg1, arg2)
    elif op == '+':
        print helpers.add(arg1, arg2)
    elif op == '*':
        print helpers.multiply(arg1, arg2)
    else:
        print "Unknown operator."
  
