#!/usr/bin/env python
import sys
import os
sys.path.insert(0, 'lib')
import helpers

while True:
    input = raw_input("Enter a simple expression: ").strip()
    if not input:
        break
    pieces = filter(None, input.split())
    if len(pieces) != 3:
        print "Bogus expression (wrong number of pieces)."
        continue
    arg1 = arg2 = None
    try:
        arg1 = float(pieces[0])
        arg2 = float(pieces[2])
    except:
        print "Non-numerical operands."
        continue
    op = pieces[1]
    if op == '-':
        print helpers.subtract(arg1, arg2)
    elif op == '+':
        print helpers.add(arg1, arg2)
    elif op == '*':
        print helpers.multiply(arg1, arg2)
    elif op == '/':
        print helpers.divide(arg1, arg2)
    else:
        print "Unknown operator."
  
